name: Run Tests

on:
  push:
    branches:
      - develop

jobs:
  run-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: test_playlistory_db
          POSTGRES_PASSWORD: adminadmin
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install dependencies
        working-directory: ./api
        run: yarn install
      - name: run tests
        working-directory: ./api
        run: yarn test

      